version: "3"
services:
  recipes-fe:
    build:
      context: "./fe/"
      dockerfile: "./Dockerfile.dev"
    ports:
      - "8080:80"
  recipes-api:
    restart: always
    build:
      context: "./be/"
      dockerfile: "./Dockerfile.dev"
    ports:
      - "3000:3000"
    env_file:
      - ".env-server"
