FROM node:lts-slim

USER root
RUN apt-get update || : && apt-get install python -y make g++

WORKDIR /home/node/app

COPY package.json . 
COPY package-lock.json . 

COPY . .
RUN npm ci

RUN npm run build

EXPOSE "$PORT"
CMD ["node", "dist/main.js"]